### ISSUE TITLE
Keep Alive Websocket Connection

### ISSUE THREAD

**Issue by baloian** [bennyn/coinbase-pro-node#100]
Hi @bennyn I found your library very interesting and I am trying to use it. However, the documentation says that connections to websocket feed are rate-limited to 1 per 4 seconds per IP. This is not related to the real-time feed data as far as you are connected right? I just want to know how does your lib handle this issue? or I have to manually reconnect?

**Comment by bennyn** [comment]
Hi @baloian, as I can see you did find out how to retrieve data for a different product (like `['LTC-USD']`)?

Regarding the listed [WebSocket rate limiting](https://docs.pro.coinbase.com/#overview): It seems like the initial connections are rate-limited (i.e. subscribing to a channel) but the data streams are not. You only have to reconnect when there is a WebSocket error. Does this answer you question?

**Comment by baloian** [comment]
Hi @bennyn thanks for the update.
Yes, I was able to figure out how to retrieve data for a different product that was my bad.

Here is the way how I handle the reconnection (this is usually pretty standard way), but it looks like the server sends to much closing signals and I am trying to figure out how I can handle it. I looked at source code and it looked like the library does not provide a method to check a websocket status right?

```
  async ListenWebsocket() {
    await this.init();

    this.client.ws.on(WebSocketEvent.ON_MESSAGE_TICKER, (ws_data) => {
      // Use data here
    });

    this.client.ws.on(WebSocketEvent.ON_ERROR, (error) => {
      Debug(error);
    });

    this.client.ws.on(WebSocketEvent.ON_CLOSE, () => {
        this.client.ws.disconnect();
        setTimeout(() => { this.ListenWebsocket() }, this.reconnect_interval_sec);
    });
  }
```

**Comment by bennyn** [comment]
Thanks for providing your code sample.

Can you please test again with [coinbase-pro-node v1.5.0](https://www.npmjs.com/package/coinbase-pro-node/v/1.5.0) (I just published it!). When do the closing signals appear? After some minutes or after some seconds? 

The WebSocket should automatically reconnect when it loses connection: https://github.com/bennyn/coinbase-pro-node/blob/v1.5.0/src/client/WebSocketClient.ts#L206-L214

**Comment by baloian** [comment]
Okay, let me test and let you know.
The closing signals appear after a couple of minutes.

**Comment by baloian** [comment]
I started getting following warnings

```
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 WebSocketEvent.ON_MESSAGE_TICKER listeners added to [WebSocketClient]. Use emitter.setMaxListeners() to increase limit
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 WebSocketEvent.ON_ERROR listeners added to [WebSocketClient]. Use emitter.setMaxListeners() to increase limit
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 WebSocketEvent.ON_CLOSE listeners added to [WebSocketClient]. Use emitter.setMaxListeners() to increase limit

```

**Comment by baloian** [comment]
I do get following socket error on ERROR, let's say sequentially. 

```
[2020-03-27T23:28:13.134Z] Coinbase Pro websocket error: ErrorEvent {
  target: ReconnectingWebSocket {
    _listeners: { error: [], message: [], open: [], close: [] },
    _retryCount: 0,
    _shouldReconnect: true,
    _connectLock: false,
    _binaryType: 'blob',
    _closeCalled: false,
    _messageQueue: [],
    onclose: [Function],
    onerror: [Function],
    onmessage: [Function],
    onopen: [Function],
    _handleOpen: [Function],
    _handleMessage: [Function],
    _handleError: [Function],
    _handleClose: [Function],
    _url: 'wss://ws-feed.pro.coinbase.com',
    _protocols: [],
    _options: {
      WebSocket: [Function],
      connectionTimeout: 4000,
      debug: false,
      maxReconnectionDelay: 10000,
      maxRetries: Infinity,
      minReconnectionDelay: 4000,
      reconnectionDelayGrowFactor: 1.3
    },
    _ws: WebSocket {
      _events: [Object: null prototype] {},
      _eventsCount: 0,
      _maxListeners: undefined,
      readyState: 2,
      protocol: '',
      _binaryType: 'nodebuffer',
      _closeFrameReceived: false,
      _closeFrameSent: false,
      _closeMessage: '',
      _closeTimer: null,
      _closeCode: 1006,
      _extensions: {},
      _receiver: null,
      _sender: null,
      _socket: null,
      _bufferedAmount: 0,
      _isServer: false,
      _redirects: 0,
      url: 'wss://ws-feed.pro.coinbase.com',
      _req: [ClientRequest]
    },
    _connectTimeout: Timeout {
      _idleTimeout: -1,
      _idlePrev: null,
      _idleNext: null,
      _idleStart: 261986,
      _onTimeout: null,
      _timerArgs: undefined,
      _repeat: null,
      _destroyed: true,
      [Symbol(refed)]: null,
      [Symbol(asyncId)]: 619231,
      [Symbol(triggerId)]: 0
    }
  },
  type: 'error',
  message: 'TIMEOUT',
  error: Error: TIMEOUT
      at ReconnectingWebSocket._handleTimeout (/var/www/cetracker/node_modules/reconnecting-websocket/dist/reconnecting-websocket-cjs.js:529:42)
      at Timeout.<anonymous> (/var/www/cetracker/node_modules/reconnecting-websocket/dist/reconnecting-websocket-cjs.js:524:75)
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7)
}
```

and after a bunch of that error I get this one

```
[2020-03-27T23:36:32.540Z] Error: socket hang up
    at connResetException (internal/errors.js:570:14)
    at TLSSocket.socketOnEnd (_http_client.js:440:23)
    at TLSSocket.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'ECONNRESET'
}

```

**Comment by baloian** [comment]
Looks like the error doesn't stop websocket, though it appears a lot, but just reporting you.

**Comment by baloian** [comment]
BTW, I am using your lib in one of my projects ([cetracker](https://github.com/baloian/cetracker)) which is an open source. Just in case you can test it and see. Again, may be I am doing something wrong not sure

**Comment by bennyn** [comment]
Hey @baloian,

I am worried about these lines:

```js
this.client.ws.disconnect();
setTimeout(() => { this.ListenWebsocket() }, this.reconnect_interval_sec);
```

WebSocket reconnection is built in the library so you don't have to do it.

I cannot reproduce the "EventEmitter memory leak" problem in my demo snippet. Does the following script shows you the same errors? 

```js
const {CoinbasePro, WebSocketEvent, WebSocketChannelName} = require('coinbase-pro-node');

const client = new CoinbasePro({
  apiKey: '',
  apiSecret: '',
  passphrase: '',
  useSandbox: false,
});

const channel = {
  name: WebSocketChannelName.TICKER,
  product_ids: ['BTC-USD', 'ETH-EUR', 'LTC-USD'],
};

client.ws.on(WebSocketEvent.ON_MESSAGE_TICKER, message => {
  console.log(`Received message of type "${message.type}".`, message);
});

client.ws.on(WebSocketEvent.ON_ERROR, (errorEvent) => {
  console.error(`There seems to be an error: ${errorEvent.message}`, errorEvent);
});

client.ws.on(WebSocketEvent.ON_CLOSE, () => {
  console.log('Do I have to reconnect or will it be done automatically?');
});

client.ws.on(WebSocketEvent.ON_OPEN, () => {
  console.log('Established connection!');
});

(async () => {
  await client.ws.connect();
  client.ws.subscribe([channel]);
})();
```

**Comment by baloian** [comment]
Hi @bennyn I removed that lines before my last comment (see git history), and I have to admit that it was a memory leak problem as I reconnect already reconnected socket. I have been running for more than 12 hours and so far no errors at all.

Thank you very much and I am closing the issue.

**Comment by bennyn** [comment]
I am very happy that we could solve your problem. Please [give a star](https://github.com/bennyn/coinbase-pro-node/stargazers) if you like this library. 😀
