### ISSUE TITLE
Feature Request: Emit Error Event on Network connection loss & heartbeat tracking

### ISSUE THREAD

**Issue by Slurpgoose** [bennyn/coinbase-pro-node#102]
Hi, Ive finished transitioning over to using this library and everything seems to be working great!

A couple things I have concerns about:

1. When network loss occurs reconnecting-websockets is able to handle reconnecting and messages automatically continue a few seconds later. Unfortunately there is no event emitted and so I am using a timer to keep track of how many subscribed markets did not receive a message per 1005ms interval (5ms to account for timer variance).

 The reason I believe this is important is because, I use a unix socket to transmit exchange snapshots to another systemd services that handle buying and selling and I want to prevent placing limit orders based on incorrect market data.

2. when reconnecting occurs `client.ws.subscribe()` is not called and therefore snapshots/last_match are not emitted. Meaning the orderbook has potential to be incorrect when a long interrupt occurs. (worst case scenario is some asks could be lower than the current bid causing a limit order to be a market order and loosing money).

At this point I am keeping track of max acceptable time disconnected and manually resubscribing.  

3. Along with using the timer to track when messages stop being emitted, I verify to make sure I receive one beat per channel subscribed per minute. My timer implementation is semi-accurate (1-5ms variation) and it seems that I miss maybe 50 out of 650,000 messages or so, in some instances they are delayed and not actually missed while other times maybe a silent reconnect occurs or some other bottleneck in my application.

Initially I had a lot more missed messages as a result of poor implementation on my end. I ended up using `clinic` and `node-tick-processor` to figure it out.

By implementing more error events new users of this library will be able to debug their issues faster.

my mistakes
- I was subscribed to too many channels (bandwidth bottleneck).
-  I was doing too much processing in this thread and after 6 or 8 hours I would get 100% cpu utilization and was not getting any indication of missing data prior to setting up my own beat tracking.

coinbase pro has a built in `sequenceId` to track messages for all channels unfortunately it seems to require being subscribed to the full channel in order for sequence numbers to be in sync and `l2_updates` do not have a sequenceId.

To combat this instead of saving the sequence number I started taking the timestamp to save `new Date(timestamp).getSeconds()` to confirm there was not a larger period than 1 second from the previous message for a product_id.

An alternative could be to count heart-beat messages per minute per product id.

**I would love to get your thoughts/criticism  on this as maybe I am overthinking something simple and doing something unnecessary.**

I am testing on `V1.15`. if adding snippets of timer code, beat tracking etc can help please let me know I will be happy to do so :)

**Comment by bennyn** [comment]
Hi @Slurpgoose, thank you for your detailed report.

You seem to have experimented a lot and I would have advised you to use the [Sequence Numbers](https://docs.pro.coinbase.com/#sequence-numbers) too.

To which channels are you actually subscribed? Just to `WebSocketChannelName.LEVEL2`?

For level 3 order books, Coinbase provides a [synchronization strategy](https://docs.pro.coinbase.com/#the-full-channel):

1. Send a `subscribe` message for the product(s) of interest and the `full` channel.
1. Queue any messages received over the websocket stream.
1. Make a REST request for the order book snapshot from the REST feed.
1. Playback queued messages, discarding sequence numbers before or equal to the snapshot sequence number.
1. Apply playback messages to the snapshot as needed (see below).
1. After playback is complete, apply real-time stream messages as they arrive.

We can approach this strategy. 

From what I read, you would like to get an event as soon as the WebSocket reconnects?

If there is a reconnect event you would know that you might have missed some messages. In such case you could [query the full order book](https://docs.pro.coinbase.com/#get-products) (REST) and apply `l2update` messages there?

**Comment by Slurpgoose** [comment]
Hey @bennyn,

to answer all your questions, I am subscribed to
```
WebSocketChannelName.LEVEL2, 
WebSocketChannelName.MATCHES
WebSocketChannelName.HEARTBEAT
```
<br>

> From what I read, you would like to get an event as soon as the WebSocket reconnects?

I would love to get notified whenever it starts the reconnecting process, but if this is not possible then that is ok. As soon as new message is emitted I will know if I missed any messages by tracking time since last message.

> If there is a reconnect event you would know that you might have missed some messages. In such case you could query the full order book (REST) and apply l2update messages there? 

yes in that scenario REST is a viable solution but due to throttling it will take longer than calling.
 `client.ws.unsubscribe(channel);` 
`client.ws.subscribe(channels);` 

After previously trying out the full channel, I came to the conclusion that synchronizing using this channel is as close to realtime as possible but is more difficult to implement and uses more cpu/bandwidth than I would prefer. (if you advise this strategy I would be willing to make the changes) but it would also require me splitting markets across child processes as I cannot handle all markets on one thread with my implementation.

Along with the synchronization strategy Coinbase also recommends [l2 updates](https://docs.pro.coinbase.com/#the-level2-channel) as the simplest solution to keep order book snapshots.

The behavior is as following:
  1. user subscribes
  2. a snapshot & last trade is emitted for each product_id
  3. user recieves  l2 updates in the following format.

    order = {
      type: 'l2update',
      product_id: 'ZRX-EUR',
      changes: [ [ 'sell', '0.130968', '0.00000' ] ],
      time: '2020-03-29T01:13:31.516175Z'
}`

Unfortunately reconnecting with `reconnecting-websockets` does not mimic the behavior of calling `client.ws.subscribe(channels);`. Therefore the snapshot message is only emitted once.

The easiest solution I can think of without reworking any of your logic is offer the ability to pass a reconnecting = false for anyone that does not want automatic reconnecting. Therefore I can use the close event to create a new connection and resubscribe.

an alternative would be to emit a warning when the client detects missed messages or when reconnecting-websockets is attempting to reconnect. Unfortunately after browsing their docs I was not able to easily find such a method. 

Also if there was a way for the library to which products are missing messages and emit an error/warning event. So a user can use API to grab trades and orderbooks for those messages.

I spent the last few hours creating this example to demonstrate what I am seeing, my exact problem and 3 hacky solutions to track messages. 

please take a look at the gist I have attached (its a working example and maybe it will be more clear than what I can put into words). If you see anything flawed in my logic please let me know, your code quality is better than what I can produce and I will be happy to receive any criticism! 

https://gist.github.com/Slurpgoose/6074c5e6e5a764463aa7a0e11f57ea16

**Comment by bennyn** [comment]
> The easiest solution I can think of without reworking any of your logic is offer the ability to pass a reconnecting = false for anyone that does not want automatic reconnecting. Therefore I can use the close event to create a new connection and resubscribe.

Hey @Slurpgoose, there is a new version (1.6.0) of "coinbase-pro-node". It addresses your request:

> The easiest solution I can think of without reworking any of your logic is offer the ability to pass a reconnecting = false for anyone that does not want automatic reconnecting. Therefore I can use the close event to create a new connection and resubscribe.

You can avoid now automatic reconnects with [options](https://github.com/pladaria/reconnecting-websocket#available-options) set to `{maxRetries: 0}`. Calling `connect` twice (without calling `disconnect` inbetween) will also cause an error as of now so you can detect if you have "zombie" handles to the WebSocket. The `connect` method does not return a `Promise` any longer and instead returns you the instance of `ReconnectingWebSocket` directly. 😀

**Comment by Slurpgoose** [comment]
Hey I just wanted to say thank you for making that change!

Setting maxRetries: 0 worked. I haven't had issues thus far. 

some messages are missed but tracking trade_ids and calling API gettrades to fill in missing gaps solved this for trades.

As well I decided to continue tracking heartbeats/second/market and calling unsubscribe & resubscribe for any market that misses more than 5 messages.

if network disconnects after connecting to channels it still takes several seconds for the socket to close even after passing `connectionTimeout: 1000`. using a timer to manually disconnect & reconnect is how im able to handle this.

Finally I added a `require('dns').lookup('google.com')` validation before calling ws.connect() to prevent enotfound and endless reconnecting when my wifi is turned off.

**Comment by bennyn** [comment]
That's great! Happy to hear that there is a solution for you now. 😀

Have you also experienced timeouts like @baloian is describing [here](https://github.com/bennyn/coinbase-pro-node/issues/108#issue-593422314)?

**Comment by Slurpgoose** [comment]
hmm I have not seen this error so far but it's only been running for a couple days in a testing environment. I will set up logging today and keep you updated if I find something I've missed

**Comment by bennyn** [comment]
Great. Thank you for your support. I made [some WebSocket improvements](https://github.com/bennyn/coinbase-pro-node/commit/59d0c7bd94189872321140be142a0397fda2c0e1) to "coinbase-pro-node". Can you please test with v1.6.1?

There is also a new [demo script](https://github.com/bennyn/coinbase-pro-node/blob/v1.6.1/src/demo-ws.ts) which shows how to use the library with WebSocket messages. It emits now a new and shiny (✨) `WebSocketEvent.ON_SUBSCRIPTION_UPDATE` event.

**Comment by Slurpgoose** [comment]
Just an update: 
Ive upgraded to  `v1.6.1` and no new issues have been discovered everything has been running smoothly for the last 4 days. I am migrating the new version into production, cheers!

**Comment by bennyn** [comment]
Cool, that makes me happy! Thanks for reporting. 🍻
