### ISSUE TITLE
Authentication is not passed to WS Client

### ISSUE THREAD

**Issue by Slurpgoose** [bennyn/coinbase-pro-node#139]
Hi @bennyn ,

its me again, unfortunately I came across a new issue in regards to `WebSocketChannelName.USER`.

`auth` config is not passed to class WebSocketClient and I was not able to find a method inside the class to retrieve a new signature.

I was able to monkey patch the latest version by passing
the configuration to WebsocketClient [here](https://github.com/bennyn/coinbase-pro-node/blob/1a25d747607c13a4b34c45c077376901fa306c87/src/CoinbasePro.ts#L45)

As well by adding a validation [here](https://github.com/bennyn/coinbase-pro-node/blob/1a25d747607c13a4b34c45c077376901fa306c87/src/client/WebSocketClient.ts#L275) 

 ```
       if (message.channels.some(channel => channel.name === 'user') && signature === undefined){
            signature= signRequest(this.auth, 'GET', '/users/self/verify');
        }
```
Although you already have implemented the logic for creating a signature in [coinbase-pro-node/src/auth](https://github.com/bennyn/coinbase-pro-node/blob/1a25d747607c13a4b34c45c077376901fa306c87/src/auth/RequestSigner.ts#L17)
I added these functions from depreciated coinbase-node package to return a signature since they were easier for me to understand.
```

const checkAuth = (auth) => {
    if (auth && !(auth.apiKey && auth.apiSecret && auth.passphrase)) {
        throw new Error(
            'Invalid or incomplete authentication credentials. Please provide all of the key, secret, and passphrase fields.',
        );
    }
    return auth || {};
};

const signRequest = (auth, method, path, options = {}) => {
    checkAuth(auth);
    const timestamp = Date.now() / 1000;
    let body = '';
    if (options.body) {
        body = JSON.stringify(options.body);
    } else if (options.qs && Object.keys(options.qs).length !== 0) {
        body = `?${querystring.stringify(options.qs)}`;
    }
    const what = timestamp + method.toUpperCase() + path + body;
    const key = Buffer.from(auth.apiSecret, 'base64');
    const hmac = crypto.createHmac('sha256', key);
    const signature = hmac.update(what).digest('base64');
    return {
        key: auth.apiKey,
        signature,
        timestamp,
        passphrase: auth.passphrase,
    };
};
```

I appreciate all the work you have done on this project and just wanted to share the issue in case I missed something or so it could be fixed in a future release.

if this solution seems reasonable (except for the 2 unnecessary functions from the old package) let me know and Id be happy to make a PR.

**Comment by bennyn** [comment]
Hey @Slurpgoose, thanks for your report. Your detailed error descriptions help me a lot and I like to make the "coinbase-pro-node" package better and better.

I knew that the day of authenticated WebSocket requests was coming. That's why the [WebSocketClient.sendMessage](https://github.com/bennyn/coinbase-pro-node/blob/v2.0.0/src/client/WebSocketClient.ts#L271) function can already consume a `signature` as second parameter. I will simplify the API so that you don't have to pass this parameter and authentication will happen automatically when an API key is given.

This is my current test scenario. It fails at the moment but I will resolve it:

```ts
import {CoinbasePro, WebSocketChannelName, WebSocketEvent} from 'coinbase-pro-node';

const client = new CoinbasePro();

const channel = {
  name: WebSocketChannelName.USER,
  product_ids: ['BTC-USD'],
};

client.ws.on(WebSocketEvent.ON_OPEN, () => {
  client.ws.subscribe(channel);
});

client.ws.on(WebSocketEvent.ON_MESSAGE_ERROR, errorMessage => {
  // Will throw: "Failed to subscribe: user channel requires authentication"
  throw new Error(`${errorMessage.message}: ${errorMessage.reason}`);
});

client.ws.connect();
```

**Comment by bennyn** [comment]
@Slurpgoose I have implemented [request singing](https://github.com/bennyn/coinbase-pro-node/pull/142) for WebSocket subscriptions. Can you please test with [v2.1.0](https://www.npmjs.com/package/coinbase-pro-node/v/2.1.0)?

Here is a snippet for testing:

```typscript
const auth = {
  apiKey: '',
  apiSecret: '',
  passphrase: '',
  useSandbox: false,
};

const client = new CoinbasePro(auth);

const channel = {
  name: WebSocketChannelName.USER,
  product_ids: ['BTC-USD'],
};

client.ws.on(WebSocketEvent.ON_MESSAGE, message => {
  console.info(`Received message of type "${message.type}".`, message);
});

client.ws.on(WebSocketEvent.ON_MESSAGE_ERROR, errorMessage => {
  throw new Error(`${errorMessage.message}: ${errorMessage.reason}`);
});

client.ws.on(WebSocketEvent.ON_OPEN, () => {
  client.ws.subscribe(channel);
});

client.ws.connect();
```

**Comment by Slurpgoose** [comment]
This is great thank you! Ive been testing for the last 24h and connecting/resubscribing works as expected :)
