### ISSUE TITLE
How get txHash?

### ISSUE THREAD

**Issue by bossikkk** [bennyn/coinbase-pro-node#146]
I detecting new deposit from getAccountHistory method, but there is no txHash in the details. How do I get a transaction hash from api? What is a details.transfer_id for?

**Comment by bennyn** [comment]
Hi @bossikkk, I searched on the official [Coinbase Pro API reference](https://docs.pro.coinbase.com/) and couldn't find anything related to "txHash" (Ethereum Transaction Hash). The code base of the [deprecated Node.js library](https://github.com/coinbase/coinbase-pro-node) for Coinbase Pro also does not show anything related. Are you sure Coinbase Pro offers such functionality? 

In your case I would ask [on Reddit](https://www.reddit.com/r/CoinBase/) or the [Coinbase Help](https://help.coinbase.com/en/contact-us.html) service.

Are you sure that the account history details return a "transfer_id"? Telling from the TypeScript definition file there is only:

```ts
export interface AccountHistoryDetails {
  order_id: string;
  product_id: string;
  trade_id: string;
}
```

**Comment by bossikkk** [comment]
Hi, I also did not find on the official website of CoinBase Pro API a mention of how to get a Transaction Hash. I just saw in the interface that there is such a functional and thought that I was missing something in API.

![image](https://user-images.githubusercontent.com/31888369/80426295-14284980-88ee-11ea-9e7e-7d62677e5c4d.png)

Anyway, thanks for the answer. I will ask Coinbase directly.

getAccountHistory method does return details with `transfer_id` and `transfer_type`, but if the `type `of the item is `transfer`:
```
{
    id: '2135804119',
    amount: '0.0000847200000000',
    balance: '0.0000847200000000',
    created_at: '2020-04-26T15:24:59.853577Z',
    type: 'transfer',
    details: {
      transfer_id: '7bc26b85-aff0-49fe-8480-118c3aea0086',
      transfer_type: 'deposit'
    }
  }
```
And I thought maybe `transfer_id` will help me in solving the problem related to detect the sender by deposit. Because of all the information about the sender that I have stored in the database, I can only check the amount.

**Comment by bennyn** [comment]
Hey @bossikkk, thanks for checking back in. Please report if you got an answer from Coinbase and let me know if we can add something to this library here to help you. I will close the issue while we have the information that we cannot get the `txHash` from the API.
