### ISSUE TITLE
CORS issue when using coinbase-pro-node in web application

### ISSUE THREAD

**Issue by linzac03** [bennyn/coinbase-pro-node#185]
EDIT:
I'm also seeing this on private endpoints not just market data endpoints. So, I am not entirely sure if there is an issue here, may just be an issue with my stack.

First off, I really appreciate the work put into this project, I think its great and I would really like to be using it long term. I'd love to contribute as well, if I am knowledgeable enough, and I'll most likely take a stab as creating a patch for this issue locally.

That being said, here is my issue:

Initially I see that in my console this appears:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api-public.sandbox.pro.coinbase.com/products/BTC-USD/candles?granularity=60. (Reason: missing token ‘cb-access-key’ in CORS header ‘Access-Control-Allow-Headers’ from CORS preflight channel)
```
I am attempting to integrate this library with a react application, using gatsbyjs. Everything imports and builds as I expect, however at runtime I see that the `cb-access-key` is checked for in every OPTIONS request:
```
Access-Control-Request-Headers | cb-access-key,cb-access-passph…cess-sign,cb-access-timestamp
-- | --
```
But, this value is not listed in the response headers:
```
access-control-allow-headers | Content-Type, Accept, cb-session, cb-fp, cb-form-factor
-- | --
```

I've seen this while trying to use the rest client, such as with the `getProductTicker()` method and while trying to get the rest-watch-candles demo code to run in browser similarly to this:
```
const WatchCandle = ({client, productId, granularity}) => {
  let [candle,setCandle] = useState({});

  async function setWatch() {
    client.rest.on(ProductEvent.NEW_CANDLE, (productId, granularity, candle) => {
      console.info('Recent candle', productId, granularity, candle.openTimeInISO);
    });

    // 3. Get latest candle
    const candles = await client.rest.product.getCandles(productId, {
      granularity,
    });
    const latestCandle = candles[candles.length - 1];
    const latestOpen = latestCandle.openTimeInISO;
    console.info('Initial candle', productId, granularity, latestOpen);

    // 4. Subscribe to upcoming candles
    client.rest.product.watchCandles(productId, granularity, latestOpen);
  }

  useEffect(() => {
    setWatch();
  });

  return (<>Waiting...</>)
}
```

For reference on why I think its an issue with looking for that `cb-access-key` token on every request to coinbase, excerpt from [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMissingAllowHeaderFromPreflight):
```
The Access-Control-Allow-Headers header is sent by the server to let the client know which headers it supports for CORS requests. The value of Access-Control-Allow-Headers should be a comma-delineated list of header names, such as "X-Custom-Information" or any of the standard but non-basic header names (which are always allowed).

This error occurs when attempting to preflight a header that is not expressly allowed (that is, it's not included in the list specified by the Access-Control-Allow-Headers header sent by the server). To fix this, the server needs to be updated so that it allows the indicated header, or you need to avoid using that header.
```

**Comment by bennyn** [comment]
Hi @linzac03, you are experiencing a CORS issue. The web browser does not allow you to communicate with the Coinbase servers from a domain which does not belong to Coinbase. 

Node.js does not have these CORS restrictions that's why this library here works with Node.js and is called "coinbase-pro-node".

In order to bypass the security restrictions set by your browser / Coinbase's servers, you will have to proxy every request that goes out to the Coinbase Pro API. You could try it out using [webpack's proxy support](https://webpack.js.org/configuration/dev-server/#devserverproxy).

You may also have a chance to use the "coinbase-pro-node" lib when disabling the security restrictions of your browser. However, that is very cumbersome and insecure: https://stackoverflow.com/a/58541689/451634

Please tell me if you had any luck using a webpack proxy and/or disabling your browser's security mechanisms.

**Comment by antriver** [comment]
This can happen if you're using `coinbase-pro-node` in a Jest test. By default, Jest will run tests using jsdom, which tries to act like a real browser. That's why you might run into CORS issues.
You can make Jest run without using jsdom by adding this to your `jest.config.js`:
```
testEnvironment: 'node',
```
