### ISSUE TITLE
Support for ETH-USD pair

### ISSUE THREAD

**Issue by TheRyanMiller** [bennyn/coinbase-pro-node#189]
In the previous deprecated version of Coinbase-pro-node, the only pairs returned when running `getProduct()`, were what is listed below. Noticeably missing is ETH-USD pair. Will this package have any support for ETH-USD pair?

- ETH-BTC
- LINK-USDC
- BTC-EUR
- BAT-USDC
- BTC-GBP
- BTC-USD

**Comment by bennyn** [comment]
I just checked with my account and the following symbols have been available: 

1. ALGO-USD
1. ATOM-BTC
1. ATOM-USD
1. BAT-ETH
1. BAT-USDC
1. BCH-BTC
1. BCH-EUR
1. BCH-GBP
1. BCH-USD
1. BTC-EUR
1. BTC-GBP
1. BTC-USD
1. BTC-USDC
1. CVC-USDC
1. DAI-USD
1. DAI-USDC
1. DASH-BTC
1. DASH-USD
1. DNT-USDC
1. EOS-BTC
1. EOS-EUR
1. EOS-USD
1. ETC-BTC
1. ETC-EUR
1. ETC-GBP
1. ETC-USD
1. ETH-BTC
1. ETH-DAI
1. ETH-EUR
1. ETH-GBP
1. ETH-USD
1. ETH-USDC
1. GNT-USDC
1. KNC-BTC
1. KNC-USD
1. LINK-ETH
1. LINK-USD
1. LOOM-USDC
1. LTC-BTC
1. LTC-EUR
1. LTC-GBP
1. LTC-USD
1. MANA-USDC
1. MKR-BTC
1. MKR-USD
1. OMG-BTC
1. OMG-EUR
1. OMG-GBP
1. OMG-USD
1. OXT-USD
1. REP-BTC
1. REP-USD
1. XLM-BTC
1. XLM-EUR
1. XLM-USD
1. XRP-BTC
1. XRP-EUR
1. XRP-USD
1. XTZ-BTC
1. XTZ-USD
1. ZEC-BTC
1. ZEC-USDC
1. ZRX-BTC
1. ZRX-EUR
1. ZRX-USD

You can test what's available for your account with the following code snippet:

```ts
const products = await client.rest.product.getProducts();
const symbols = products.map(symbol => symbol.id);
console.log(symbols.sort().join(', '));
```

**Comment by TheRyanMiller** [comment]
Thanks @bennyn , really appreciate your reply. Your script, like mine results in the same 6 "products" in my original post. ETH-USD not available, despite the fact I can trade this same product via the CBP web app.  
I've concluded this must be some restriction on my API account. Since I can't find anything about this in their docs, I have submitted a support ticket to Coinbase to see if they're able to help grant the full set of products to my API account.

- BAT-USDC
- BTC-EUR
- BTC-GBP
- BTC-USD
- ETH-BTC
- LINK-USDC

**Comment by TheRyanMiller** [comment]
Hi - I realized what my problem is. I was connected to the Sandbox when running `.getProducts() ` as opposed to the production API. When I switch over, I see everything.
My sandbox environment only provides access to that limited subset of pairs/products. Is this the same for everyone? 
If so, this makes testing quite a bit harder, no?

**Comment by bennyn** [comment]
I also have only a limited amount of products when using the Sandbox environment. It does not make testing harder because all the product operations work the same.
