### ISSUE TITLE
MIssing api functionality

### ISSUE THREAD

**Issue by duncanelliot** [bennyn/coinbase-pro-node#260]
Hi there,

Not an issue but more like a feature request.

Right now the functionality to delete individual orders is missing (I think)

If I can work out how to do pull request, I'll have a stab at implementing it.

Thanks for your work!

**Comment by bennyn** [comment]
Hi @duncanelliot, please let me know which API resource you are missing and I will help you to get it implemented. 

From what I understood you want to cancel a pending (not filled) order?

**Comment by bennyn** [comment]
Closed because of inactivity.

**Comment by definitelycarter** [comment]
Hi @bennyn - It looks like the ability to cancel a single order is missing from the library.  Here are the docs for canceling a sing order - https://docs.pro.coinbase.com/#cancel-an-order

**Comment by bennyn** [comment]
@duncanelliot & @definitelycarter thanks for your input and contributions. The "cancel order" functionality is now live with [**v2.12.0**](https://www.npmjs.com/package/coinbase-pro-node/v/2.12.0).
