### ISSUE TITLE
Issue with WS Documentation

### ISSUE THREAD

**Issue by Slurpgoose** [bennyn/coinbase-pro-node#84]
Hey thanks for building and maintaining this package. I was attempting to migrate from depreciated coinbase-pro package and unfortunately, my event listeners are not firing using the example provided in the docs.

 I attempted to go through the code in  coinbase-pro-node/src/client/WebSocketClient.ts and I was not able to even find `subscribeToTickers`  method in src. I do not have a good grasp of typescript so it could be part of the problem.

 (I created a simplified gist using the old package), would it be possible for me to implement an identical/similar system for handling WS messages as I have done below?

**1. Subscribe to multiple channels ex `['ticker', 'full']`
2. receive all channel updates to one event listener  `[WebSocketEvent.ON_MESSAGE']` so I can redirect them to a switch statement.
3. store an instance of the socket and resubscribe/ destroy recreate**

https://gist.github.com/Slurpgoose/ab41a4674a7a353b8f68b9d80af2b004

Also if this is possible will I need to import WebSocketEvent, WebSocketChannelName objects to access these methods or are they inherited from `new CoinbasePro(auth)`? Or am I able to subscribe using a string.

**Comment by bennyn** [comment]
Hi @Slurpgoose, thank you for your valuable feedback!

I am happy to assist you with the migration from "[coinbase-pro](https://www.npmjs.com/package/coinbase-pro)" to "[coinbase-pro-node](https://www.npmjs.com/package/coinbase-pro-node)".

The `subscribeToTickers` method was replaced with the following:

```ts
client.ws.subscribe({
  name: WebSocketChannelName.TICKER,
  product_ids: ['BTC-USD', 'ETH-EUR'],
});
```

Subscribing to multiple channels and "one event listener to rule them all" is not yet implemented but I will add these to my TODOs. 📑

I just updated the [WebSocket subscription example](https://github.com/bennyn/coinbase-pro-node#websocket-example), so you can look up how to import `WebSocketEvent` and `WebSocketChannelName`.

**Comment by Slurpgoose** [comment]
@bennyn Thanks for your quick response! the changes to the documentation make everything a lot more clear. I will check it out tonight and let you know if I have any more questions.

**Comment by bennyn** [comment]
Hi @Slurpgoose, today I merged the functionality to [subscribe to multiple channels](https://github.com/bennyn/coinbase-pro-node/pull/92) in one go.

It works like this:

```ts
const symbol = 'BTC-USD';

client.ws.on(WebSocketEvent.ON_MESSAGE, (message) => {
  console.log(`Received message type "${message.type}"...`, JSON.stringify(message));
});

await client.ws.connect();

client.ws.subscribe([
  {
    name: WebSocketChannelName.STATUS,
    product_ids: [symbol],
  },
  {
    name: WebSocketChannelName.MATCHES,
    product_ids: [symbol],
  }
]);
```

This means 1 & 2 from your checklist are done. Can you give me more insights about "store an instance of the socket and resubscribe"? How should it work and can you maybe draft a PR for this?

**Comment by bfailing** [comment]
@bennyn In your latest example, if an "ON_OPEN" handler is added, does it fire after `connect()` and before `subscribe()`?

**Comment by bennyn** [comment]
Hey @bfailing, yes, `WebSocketEvent.ON_OPEN` will fire after calling `client.ws.connect` and before `client.ws.subscribe`.

**Comment by Slurpgoose** [comment]
@bennyn Thank You for the hard work. After reading through the examples this will fit my use case perfectly. I do not think anything extra needs to be done at this point as I can store an instance of 
`new CoinbasePro()` and use 

    ws.disconnect();
    ws.unsubscribe([channel]);

I am maintaining a trading application and storing exchange state locally for all markets. I will continue to dive into the codebase this week and will be more than happy to contribute in the future.

**Comment by bennyn** [comment]
I am happy that I could help. Thank you also for marking this project with a star! ⭐

Let me know if I can support you further. As a library author, feedback from users is important to me. 🙂
