### ISSUE TITLE
How to Get Complete Response from getCandles()

### ISSUE THREAD

**Issue by bfailing** [bennyn/coinbase-pro-node#98]
The following seems to only return the body from the response:
````
client.rest.product.getCandles('BTC-USD', {
  granularity: CandleGranularity.ONE_HOUR,
  start: start_time,
  end: end_time
});
````
How do you get the complete response including, e.g., the status code?

**Comment by bennyn** [comment]
Hi @bfailing, it is by design that only data is returned. Why would you need more than this? If there is an error you will get the full HTTP response (with status code, etc.).

**Comment by bfailing** [comment]
To test this (i.e. hit a rate limit), I need to disable the rate limiting in your code.  How do I do that?

**Comment by bennyn** [comment]
Thie rate limiting is implemented here: https://github.com/bennyn/coinbase-pro-node/blob/v1.4.1/src/client/RESTClient.ts#L42-L48

**Comment by bennyn** [comment]
@bfailing here is an example how you can catch errors with additional information (you will get everything which `AxiosError` provides):

```ts
import {AxiosError} from 'axios';
import {CoinbasePro} from 'coinbase-pro-node';

// [...]

client.rest.product.getCandles('DOES-BOT-EXIST').catch((error: AxiosError) => {
  console.error(`Request failed when querying "${error.config.url}": ${error.message}`);
});
```

I hope this answers your question. Please [leave me a star](https://github.com/bennyn/coinbase-pro-node/stargazers) if it does. ⭐
